; PlatformIO Project Configuration
; Endüstriyel IoT Gateway - ESP32 Firmware

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DFIRMWARE_VERSION=\"0.1.0\"

lib_deps =
    emelianov/modbus-esp8266@^4.1.0          ; eModbus - RTU master
    knolleary/PubSubClient@^2.8              ; MQTT client
    bblanchon/ArduinoJson@^7.0.4             ; JSON parse/serialize
    https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.6.0   ; Async HTTP server (community fork)
    https://github.com/ESP32Async/AsyncTCP.git#v3.3.2            ; AsyncTCP (community fork)
    adafruit/Adafruit SSD1306@^2.5.9         ; OLED
    adafruit/Adafruit GFX Library@^1.11.9
    tzapu/WiFiManager@^2.0.17                ; WiFi provisioning portal
